name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Exécuter sur chaque push vers la branche principale
  pull_request:
    branches:
      - main  # Exécuter également sur chaque PR vers la branche principale

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter les tests unitaires
      - name: Run unit tests
        run: |
          unittest tests/

      # Étape 5 (optionnelle) : Déployer l'API (après tests réussis)
      - name: Deploy API
        if: success()
        run: |
          echo "Deploying API..."  # Commande ou script de déploiement réel
